### ISSUE TITLE
Reverse quick hacks

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBExports#19]
I made the following changes to `inst/scripts/full_dump.csv` that need to be reversed when possible. I also manually pushed a `full_dump.csv` and `bugsigdb_signatures_mixed_metaphlan.gmt` as 5eeb4cb479c5f4fec822b91e1a26752bdf3913ac in the interim.

- [x] Uncomment when https://github.com/waldronlab/BugSigDB/issues/177 is resolved:
`# sigs <- subset(sigs, State == "Complete")`

- [x] Undo once problem in genus/species/ncbi/taxname calls to `bugsigdb::makeSignatures()` is resolved (still not sure where the problem is):
```r
# tax.levels <- c("mixed", "genus", "species")
# id.types <- c("ncbi", "metaphlan", "taxname")
tax.levels <- c("mixed")
id.types <- c("metaphlan")
exact.tax.levels <- c(TRUE, FALSE)
```

**Comment by lwaldron** [comment]
The second problem may be also be resolved when the upstream issue is fixed, since BSDB names also got broken. 

When this is all resolved @jwokaty, would you 
1. add a GHA badge to the README.md, 
2. make the cron job daily instead of weekly (I think bugsigdb.org re-creates the export files daily, so timed a little after when that happens and ensuring the GHA silently finishes without commit if there are no changes since the last commit, 
3. treat errors in this action as urgent because they will block the work of analysts who can't access recent changes to bugsigdb.org (see e.g. Sharmila today in #bsdb-discussion), and 
4. update https://bugsigdb.org/Help:Contents#Information_for_data_analysts_and_tool_developers and https://bugsigdb.org/Project:About#Data_licensing to reflect the changes to reflect these changes ?

@lgeistlinger I think the bugsigdbr vignette and import function should make clearer what the "devel" version does (and maybe even a message when using this option), because every active user is asking when changes to the wiki will be accessible from R.

**Comment by lwaldron** [comment]
Upstream issue is resolved, but calls to `bugsigdb::makeSignatures()` are still not working. dump_release.R seems to be inferring taxonomic rank in a way that only works for Metaphlan names, so I'm not sure how to fix it. @lgeistlinger would you take a look?

**Comment by lgeistlinger** [comment]
Ok the problem was an empty string taxon in Study 496, Experiment 1, Signature 1 - where somebody seemed to have tried to add the NCBI Taxon ID "18997" - which however does not exist (anymore?). This resulted in an empty string taxon `""` in the export which caused the parser to break at the step of writing the GMT files.  

I resolved this by:

1. Removing the taxon "18997" from Study 496, Experiment 1, Signature 1 directly on bugsigdb.org
2. Removed any such empty string instances from the signatures before writing to GMT.

The script now runs without error locally for me and also here on the GHA.
However there seems now a hiccup in the GHA due to the manual commits of `full_dump.csv` and `bugsigdb_signatures_mixed_metaphlan.gmt` in the `Commit Exports` step:

<img width="791" alt="Screen Shot 2023-04-20 at 7 25 54 PM" src="https://user-images.githubusercontent.com/11871050/233507079-a528aa1e-f64f-4f7a-a3da-4c1b0212a299.png">

@jwokaty could you please take a look?

**Comment by lwaldron** [comment]
Nice work Ludwig! It’s likely a taxon that has been deprecated since it was
entered, something we’ll eventually have to deal with on the wiki side.

@jwokaty I manually pushed the full_dump.csv and Metaphlan mixed gmt files.
-- 

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by jwokaty** [comment]
The action is now working. Since there is a separate issue for https://github.com/waldronlab/BugSigDBExports/issues/19#issuecomment-1515679971, is this okay to close?

**Comment by lgeistlinger** [comment]
Thanks! Yes this can be closed and I think we can proceed with regard to https://github.com/waldronlab/BugSigDBExports/issues/19#issuecomment-1515679971 on the separate issues #20 and https://github.com/waldronlab/bugsigdbr/issues/39.
